package gameoflife.ui;

import gameoflife.core.Universe;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 * This class implements the main GUI screen of the Game of Life simulation
 * and display the visual panel to show the universe with cells and also a configuration
 * panel for simulation settings.
 * 
 * @author
 */
public class MainScreenFrame extends javax.swing.JFrame {

    /** instance of the Universe */
    private Universe universe;
    
    /** instance of the panel displaying the universe */
    private UniversePanel universePanel;
    
    
    /**
     * Creates new form MainScreenFrame
     */
    public MainScreenFrame() {
        initComponents();
        
        universe = new Universe();        
        universePanel = new UniversePanel(universe);        
        jPanelCenter.add(universePanel, BorderLayout.CENTER);
        txtWidth.setText(universe.getWidth()+"");
        txtHeight.setText(universe.getHeight()+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCenter = new javax.swing.JPanel();
        jPanelSouth = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtWidth = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnRun = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conway's Game of Life");

        jPanelCenter.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jPanelSouth.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        jLabel1.setText("Width:");
        jPanelSouth.add(jLabel1);

        txtWidth.setColumns(5);
        jPanelSouth.add(txtWidth);

        jLabel2.setText("Height:");
        jPanelSouth.add(jLabel2);

        txtHeight.setColumns(5);
        jPanelSouth.add(txtHeight);

        btnReset.setText("Reset Universe");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanelSouth.add(btnReset);

        btnRun.setText("Run");
        jPanelSouth.add(btnRun);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanelSouth.add(btnExit);

        btnHelp.setText("Help");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        jPanelSouth.add(btnHelp);

        getContentPane().add(jPanelSouth, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        int width;
        int height;
        String widthInput = txtWidth.getText();
        String heightInput = txtHeight.getText();
        try{
            width = Integer.parseInt(widthInput);
            height = Integer.parseInt(heightInput);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Invalid width/height specified !");
            return;
        }
        universe.setSize(width, height);
        repaint();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        // TODO add your handling code here:
        HelpDialog helpDlg = new HelpDialog(this, true);
        helpDlg.setLocationRelativeTo(this);
        helpDlg.setVisible(true);
    }//GEN-LAST:event_btnHelpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnRun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelSouth;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtWidth;
    // End of variables declaration//GEN-END:variables
}
